<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use DB;
class KotaSeeder extends Seeder{

    public function run()
    {
        DB::table('kotas')->insert([
            ['id' => '1101','kode_kota' => '1101','provinsi_id' => '11','nama_kota' => 'KABUPATEN SIMEULUE'],
            ['id' => '1102','kode_kota' => '1102','provinsi_id' => '11','nama_kota' => 'KABUPATEN ACEH SINGKIL'],
            ['id' => '1103','kode_kota' => '1103','provinsi_id' => '11','nama_kota' => 'KABUPATEN ACEH SELATAN'],
            ['id' => '1104','kode_kota' => '1104','provinsi_id' => '11','nama_kota' => 'KABUPATEN ACEH TENGGARA'],
            ['id' => '1105','kode_kota' => '1105','provinsi_id' => '11','nama_kota' => 'KABUPATEN ACEH TIMUR'],
            ['id' => '1106','kode_kota' => '1106','provinsi_id' => '11','nama_kota' => 'KABUPATEN ACEH TENGAH'],
            ['id' => '1107','kode_kota' => '1107','provinsi_id' => '11','nama_kota' => 'KABUPATEN ACEH BARAT'],
            ['id' => '1108','kode_kota' => '1108','provinsi_id' => '11','nama_kota' => 'KABUPATEN ACEH BESAR'],
            ['id' => '1109','kode_kota' => '1109','provinsi_id' => '11','nama_kota' => 'KABUPATEN PIDIE'],
            ['id' => '1110','kode_kota' => '1110','provinsi_id' => '11','nama_kota' => 'KABUPATEN BIREUEN'],
            ['id' => '1111','kode_kota' => '1111','provinsi_id' => '11','nama_kota' => 'KABUPATEN ACEH UTARA'],
            ['id' => '1112','kode_kota' => '1112','provinsi_id' => '11','nama_kota' => 'KABUPATEN ACEH BARAT DAYA'],
            ['id' => '1113','kode_kota' => '1113','provinsi_id' => '11','nama_kota' => 'KABUPATEN GAYO LUES'],
            ['id' => '1114','kode_kota' => '1114','provinsi_id' => '11','nama_kota' => 'KABUPATEN ACEH TAMIANG'],
            ['id' => '1115','kode_kota' => '1115','provinsi_id' => '11','nama_kota' => 'KABUPATEN NAGAN RAYA'],
            ['id' => '1116','kode_kota' => '1116','provinsi_id' => '11','nama_kota' => 'KABUPATEN ACEH JAYA'],
            ['id' => '1117','kode_kota' => '1117','provinsi_id' => '11','nama_kota' => 'KABUPATEN BENER MERIAH'],
            ['id' => '1118','kode_kota' => '1118','provinsi_id' => '11','nama_kota' => 'KABUPATEN PIDIE JAYA'],
            ['id' => '1171','kode_kota' => '1171','provinsi_id' => '11','nama_kota' => 'KOTA BANDA ACEH'],
            ['id' => '1172','kode_kota' => '1172','provinsi_id' => '11','nama_kota' => 'KOTA SABANG'],
            ['id' => '1173','kode_kota' => '1173','provinsi_id' => '11','nama_kota' => 'KOTA LANGSA'],
            ['id' => '1174','kode_kota' => '1174','provinsi_id' => '11','nama_kota' => 'KOTA LHOKSEUMAWE'],
            ['id' => '1175','kode_kota' => '1175','provinsi_id' => '11','nama_kota' => 'KOTA SUBULUSSALAM'],
            ['id' => '1201','kode_kota' => '1201','provinsi_id' => '12','nama_kota' => 'KABUPATEN NIAS'],
            ['id' => '1202','kode_kota' => '1202','provinsi_id' => '12','nama_kota' => 'KABUPATEN MANDAILING NATAL'],
            ['id' => '1203','kode_kota' => '1203','provinsi_id' => '12','nama_kota' => 'KABUPATEN TAPANULI SELATAN'],
            ['id' => '1204','kode_kota' => '1204','provinsi_id' => '12','nama_kota' => 'KABUPATEN TAPANULI TENGAH'],
            ['id' => '1205','kode_kota' => '1205','provinsi_id' => '12','nama_kota' => 'KABUPATEN TAPANULI UTARA'],
            ['id' => '1206','kode_kota' => '1206','provinsi_id' => '12','nama_kota' => 'KABUPATEN TOBA SAMOSIR'],
            ['id' => '1207','kode_kota' => '1207','provinsi_id' => '12','nama_kota' => 'KABUPATEN LABUHAN BATU'],
            ['id' => '1208','kode_kota' => '1208','provinsi_id' => '12','nama_kota' => 'KABUPATEN ASAHAN'],
            ['id' => '1209','kode_kota' => '1209','provinsi_id' => '12','nama_kota' => 'KABUPATEN SIMALUNGUN'],
            ['id' => '1210','kode_kota' => '1210','provinsi_id' => '12','nama_kota' => 'KABUPATEN DAIRI'],
            ['id' => '1211','kode_kota' => '1211','provinsi_id' => '12','nama_kota' => 'KABUPATEN KARO'],
            ['id' => '1212','kode_kota' => '1212','provinsi_id' => '12','nama_kota' => 'KABUPATEN DELI SERDANG'],
            ['id' => '1213','kode_kota' => '1213','provinsi_id' => '12','nama_kota' => 'KABUPATEN LANGKAT'],
            ['id' => '1214','kode_kota' => '1214','provinsi_id' => '12','nama_kota' => 'KABUPATEN NIAS SELATAN'],
            ['id' => '1215','kode_kota' => '1215','provinsi_id' => '12','nama_kota' => 'KABUPATEN HUMBANG HASUNDUTAN'],
            ['id' => '1216','kode_kota' => '1216','provinsi_id' => '12','nama_kota' => 'KABUPATEN PAKPAK BHARAT'],
            ['id' => '1217','kode_kota' => '1217','provinsi_id' => '12','nama_kota' => 'KABUPATEN SAMOSIR'],
            ['id' => '1218','kode_kota' => '1218','provinsi_id' => '12','nama_kota' => 'KABUPATEN SERDANG BEDAGAI'],
            ['id' => '1219','kode_kota' => '1219','provinsi_id' => '12','nama_kota' => 'KABUPATEN BATU BARA'],
            ['id' => '1220','kode_kota' => '1220','provinsi_id' => '12','nama_kota' => 'KABUPATEN PADANG LAWAS UTARA'],
            ['id' => '1221','kode_kota' => '1221','provinsi_id' => '12','nama_kota' => 'KABUPATEN PADANG LAWAS'],
            ['id' => '1222','kode_kota' => '1222','provinsi_id' => '12','nama_kota' => 'KABUPATEN LABUHAN BATU SELATAN'],
            ['id' => '1223','kode_kota' => '1223','provinsi_id' => '12','nama_kota' => 'KABUPATEN LABUHAN BATU UTARA'],
            ['id' => '1224','kode_kota' => '1224','provinsi_id' => '12','nama_kota' => 'KABUPATEN NIAS UTARA'],
            ['id' => '1225','kode_kota' => '1225','provinsi_id' => '12','nama_kota' => 'KABUPATEN NIAS BARAT'],
            ['id' => '1271','kode_kota' => '1271','provinsi_id' => '12','nama_kota' => 'KOTA SIBOLGA'],
            ['id' => '1272','kode_kota' => '1272','provinsi_id' => '12','nama_kota' => 'KOTA TANJUNG BALAI'],
            ['id' => '1273','kode_kota' => '1273','provinsi_id' => '12','nama_kota' => 'KOTA PEMATANG SIANTAR'],
            ['id' => '1274','kode_kota' => '1274','provinsi_id' => '12','nama_kota' => 'KOTA TEBING TINGGI'],
            ['id' => '1275','kode_kota' => '1275','provinsi_id' => '12','nama_kota' => 'KOTA MEDAN'],
            ['id' => '1276','kode_kota' => '1276','provinsi_id' => '12','nama_kota' => 'KOTA BINJAI'],
            ['id' => '1277','kode_kota' => '1277','provinsi_id' => '12','nama_kota' => 'KOTA PADANGSIDIMPUAN'],
            ['id' => '1278','kode_kota' => '1278','provinsi_id' => '12','nama_kota' => 'KOTA GUNUNGSITOLI'],
            ['id' => '1301','kode_kota' => '1301','provinsi_id' => '13','nama_kota' => 'KABUPATEN KEPULAUAN MENTAWAI'],
            ['id' => '1302','kode_kota' => '1302','provinsi_id' => '13','nama_kota' => 'KABUPATEN PESISIR SELATAN'],
            ['id' => '1303','kode_kota' => '1303','provinsi_id' => '13','nama_kota' => 'KABUPATEN SOLOK'],
            ['id' => '1304','kode_kota' => '1304','provinsi_id' => '13','nama_kota' => 'KABUPATEN SIJUNJUNG'],
            ['id' => '1305','kode_kota' => '1305','provinsi_id' => '13','nama_kota' => 'KABUPATEN TANAH DATAR'],
            ['id' => '1306','kode_kota' => '1306','provinsi_id' => '13','nama_kota' => 'KABUPATEN PADANG PARIAMAN'],
            ['id' => '1307','kode_kota' => '1307','provinsi_id' => '13','nama_kota' => 'KABUPATEN AGAM'],
            ['id' => '1308','kode_kota' => '1308','provinsi_id' => '13','nama_kota' => 'KABUPATEN LIMA PULUH KOTA'],
            ['id' => '1309','kode_kota' => '1309','provinsi_id' => '13','nama_kota' => 'KABUPATEN PASAMAN'],
            ['id' => '1310','kode_kota' => '1310','provinsi_id' => '13','nama_kota' => 'KABUPATEN SOLOK SELATAN'],
            ['id' => '1311','kode_kota' => '1311','provinsi_id' => '13','nama_kota' => 'KABUPATEN DHARMASRAYA'],
            ['id' => '1312','kode_kota' => '1312','provinsi_id' => '13','nama_kota' => 'KABUPATEN PASAMAN BARAT'],
            ['id' => '1371','kode_kota' => '1371','provinsi_id' => '13','nama_kota' => 'KOTA PADANG'],
            ['id' => '1372','kode_kota' => '1372','provinsi_id' => '13','nama_kota' => 'KOTA SOLOK'],
            ['id' => '1373','kode_kota' => '1373','provinsi_id' => '13','nama_kota' => 'KOTA SAWAH LUNTO'],
            ['id' => '1374','kode_kota' => '1374','provinsi_id' => '13','nama_kota' => 'KOTA PADANG PANJANG'],
            ['id' => '1375','kode_kota' => '1375','provinsi_id' => '13','nama_kota' => 'KOTA BUKITTINGGI'],
            ['id' => '1376','kode_kota' => '1376','provinsi_id' => '13','nama_kota' => 'KOTA PAYAKUMBUH'],
            ['id' => '1377','kode_kota' => '1377','provinsi_id' => '13','nama_kota' => 'KOTA PARIAMAN'],
            ['id' => '1401','kode_kota' => '1401','provinsi_id' => '14','nama_kota' => 'KABUPATEN KUANTAN SINGINGI'],
            ['id' => '1402','kode_kota' => '1402','provinsi_id' => '14','nama_kota' => 'KABUPATEN INDRAGIRI HULU'],
            ['id' => '1403','kode_kota' => '1403','provinsi_id' => '14','nama_kota' => 'KABUPATEN INDRAGIRI HILIR'],
            ['id' => '1404','kode_kota' => '1404','provinsi_id' => '14','nama_kota' => 'KABUPATEN PELALAWAN'],
            ['id' => '1405','kode_kota' => '1405','provinsi_id' => '14','nama_kota' => 'KABUPATEN SIAK'],
            ['id' => '1406','kode_kota' => '1406','provinsi_id' => '14','nama_kota' => 'KABUPATEN KAMPAR'],
            ['id' => '1407','kode_kota' => '1407','provinsi_id' => '14','nama_kota' => 'KABUPATEN ROKAN HULU'],
            ['id' => '1408','kode_kota' => '1408','provinsi_id' => '14','nama_kota' => 'KABUPATEN BENGKALIS'],
            ['id' => '1409','kode_kota' => '1409','provinsi_id' => '14','nama_kota' => 'KABUPATEN ROKAN HILIR'],
            ['id' => '1410','kode_kota' => '1410','provinsi_id' => '14','nama_kota' => 'KABUPATEN KEPULAUAN MERANTI'],
            ['id' => '1471','kode_kota' => '1471','provinsi_id' => '14','nama_kota' => 'KOTA PEKANBARU'],
            ['id' => '1473','kode_kota' => '1473','provinsi_id' => '14','nama_kota' => 'KOTA DUMAI'],
            ['id' => '1501','kode_kota' => '1501','provinsi_id' => '15','nama_kota' => 'KABUPATEN KERINCI'],
            ['id' => '1502','kode_kota' => '1502','provinsi_id' => '15','nama_kota' => 'KABUPATEN MERANGIN'],
            ['id' => '1503','kode_kota' => '1503','provinsi_id' => '15','nama_kota' => 'KABUPATEN SAROLANGUN'],
            ['id' => '1504','kode_kota' => '1504','provinsi_id' => '15','nama_kota' => 'KABUPATEN BATANG HARI'],
            ['id' => '1505','kode_kota' => '1505','provinsi_id' => '15','nama_kota' => 'KABUPATEN MUARO JAMBI'],
            ['id' => '1506','kode_kota' => '1506','provinsi_id' => '15','nama_kota' => 'KABUPATEN TANJUNG JABUNG TIMUR'],
            ['id' => '1507','kode_kota' => '1507','provinsi_id' => '15','nama_kota' => 'KABUPATEN TANJUNG JABUNG BARAT'],
            ['id' => '1508','kode_kota' => '1508','provinsi_id' => '15','nama_kota' => 'KABUPATEN TEBO'],
            ['id' => '1509','kode_kota' => '1509','provinsi_id' => '15','nama_kota' => 'KABUPATEN BUNGO'],
            ['id' => '1571','kode_kota' => '1571','provinsi_id' => '15','nama_kota' => 'KOTA JAMBI'],
            ['id' => '1572','kode_kota' => '1572','provinsi_id' => '15','nama_kota' => 'KOTA SUNGAI PENUH'],
            ['id' => '1601','kode_kota' => '1601','provinsi_id' => '16','nama_kota' => 'KABUPATEN OGAN KOMERING ULU'],
            ['id' => '1602','kode_kota' => '1602','provinsi_id' => '16','nama_kota' => 'KABUPATEN OGAN KOMERING ILIR'],
            ['id' => '1603','kode_kota' => '1603','provinsi_id' => '16','nama_kota' => 'KABUPATEN MUARA ENIM'],
            ['id' => '1604','kode_kota' => '1604','provinsi_id' => '16','nama_kota' => 'KABUPATEN LAHAT'],
            ['id' => '1605','kode_kota' => '1605','provinsi_id' => '16','nama_kota' => 'KABUPATEN MUSI RAWAS'],
            ['id' => '1606','kode_kota' => '1606','provinsi_id' => '16','nama_kota' => 'KABUPATEN MUSI BANYUASIN'],
            ['id' => '1607','kode_kota' => '1607','provinsi_id' => '16','nama_kota' => 'KABUPATEN BANYU ASIN'],
            ['id' => '1608','kode_kota' => '1608','provinsi_id' => '16','nama_kota' => 'KABUPATEN OGAN KOMERING ULU SELATAN'],
            ['id' => '1609','kode_kota' => '1609','provinsi_id' => '16','nama_kota' => 'KABUPATEN OGAN KOMERING ULU TIMUR'],
            ['id' => '1610','kode_kota' => '1610','provinsi_id' => '16','nama_kota' => 'KABUPATEN OGAN ILIR'],
            ['id' => '1611','kode_kota' => '1611','provinsi_id' => '16','nama_kota' => 'KABUPATEN EMPAT LAWANG'],
            ['id' => '1612','kode_kota' => '1612','provinsi_id' => '16','nama_kota' => 'KABUPATEN PENUKAL ABAB LEMATANG ILIR'],
            ['id' => '1613','kode_kota' => '1613','provinsi_id' => '16','nama_kota' => 'KABUPATEN MUSI RAWAS UTARA'],
            ['id' => '1671','kode_kota' => '1671','provinsi_id' => '16','nama_kota' => 'KOTA PALEMBANG'],
            ['id' => '1672','kode_kota' => '1672','provinsi_id' => '16','nama_kota' => 'KOTA PRABUMULIH'],
            ['id' => '1673','kode_kota' => '1673','provinsi_id' => '16','nama_kota' => 'KOTA PAGAR ALAM'],
            ['id' => '1674','kode_kota' => '1674','provinsi_id' => '16','nama_kota' => 'KOTA LUBUKLINGGAU'],
            ['id' => '1701','kode_kota' => '1701','provinsi_id' => '17','nama_kota' => 'KABUPATEN BENGKULU SELATAN'],
            ['id' => '1702','kode_kota' => '1702','provinsi_id' => '17','nama_kota' => 'KABUPATEN REJANG LEBONG'],
            ['id' => '1703','kode_kota' => '1703','provinsi_id' => '17','nama_kota' => 'KABUPATEN BENGKULU UTARA'],
            ['id' => '1704','kode_kota' => '1704','provinsi_id' => '17','nama_kota' => 'KABUPATEN KAUR'],
            ['id' => '1705','kode_kota' => '1705','provinsi_id' => '17','nama_kota' => 'KABUPATEN SELUMA'],
            ['id' => '1706','kode_kota' => '1706','provinsi_id' => '17','nama_kota' => 'KABUPATEN MUKOMUKO'],
            ['id' => '1707','kode_kota' => '1707','provinsi_id' => '17','nama_kota' => 'KABUPATEN LEBONG'],
            ['id' => '1708','kode_kota' => '1708','provinsi_id' => '17','nama_kota' => 'KABUPATEN KEPAHIANG'],
            ['id' => '1709','kode_kota' => '1709','provinsi_id' => '17','nama_kota' => 'KABUPATEN BENGKULU TENGAH'],
            ['id' => '1771','kode_kota' => '1771','provinsi_id' => '17','nama_kota' => 'KOTA BENGKULU'],
            ['id' => '1801','kode_kota' => '1801','provinsi_id' => '18','nama_kota' => 'KABUPATEN LAMPUNG BARAT'],
            ['id' => '1802','kode_kota' => '1802','provinsi_id' => '18','nama_kota' => 'KABUPATEN TANGGAMUS'],
            ['id' => '1803','kode_kota' => '1803','provinsi_id' => '18','nama_kota' => 'KABUPATEN LAMPUNG SELATAN'],
            ['id' => '1804','kode_kota' => '1804','provinsi_id' => '18','nama_kota' => 'KABUPATEN LAMPUNG TIMUR'],
            ['id' => '1805','kode_kota' => '1805','provinsi_id' => '18','nama_kota' => 'KABUPATEN LAMPUNG TENGAH'],
            ['id' => '1806','kode_kota' => '1806','provinsi_id' => '18','nama_kota' => 'KABUPATEN LAMPUNG UTARA'],
            ['id' => '1807','kode_kota' => '1807','provinsi_id' => '18','nama_kota' => 'KABUPATEN WAY KANAN'],
            ['id' => '1808','kode_kota' => '1808','provinsi_id' => '18','nama_kota' => 'KABUPATEN TULANGBAWANG'],
            ['id' => '1809','kode_kota' => '1809','provinsi_id' => '18','nama_kota' => 'KABUPATEN PESAWARAN'],
            ['id' => '1810','kode_kota' => '1810','provinsi_id' => '18','nama_kota' => 'KABUPATEN PRINGSEWU'],
            ['id' => '1811','kode_kota' => '1811','provinsi_id' => '18','nama_kota' => 'KABUPATEN MESUJI'],
            ['id' => '1812','kode_kota' => '1812','provinsi_id' => '18','nama_kota' => 'KABUPATEN TULANG BAWANG BARAT'],
            ['id' => '1813','kode_kota' => '1813','provinsi_id' => '18','nama_kota' => 'KABUPATEN PESISIR BARAT'],
            ['id' => '1871','kode_kota' => '1871','provinsi_id' => '18','nama_kota' => 'KOTA BANDAR LAMPUNG'],
            ['id' => '1872','kode_kota' => '1872','provinsi_id' => '18','nama_kota' => 'KOTA METRO'],
            ['id' => '1901','kode_kota' => '1901','provinsi_id' => '19','nama_kota' => 'KABUPATEN BANGKA'],
            ['id' => '1902','kode_kota' => '1902','provinsi_id' => '19','nama_kota' => 'KABUPATEN BELITUNG'],
            ['id' => '1903','kode_kota' => '1903','provinsi_id' => '19','nama_kota' => 'KABUPATEN BANGKA BARAT'],
            ['id' => '1904','kode_kota' => '1904','provinsi_id' => '19','nama_kota' => 'KABUPATEN BANGKA TENGAH'],
            ['id' => '1905','kode_kota' => '1905','provinsi_id' => '19','nama_kota' => 'KABUPATEN BANGKA SELATAN'],
            ['id' => '1906','kode_kota' => '1906','provinsi_id' => '19','nama_kota' => 'KABUPATEN BELITUNG TIMUR'],
            ['id' => '1971','kode_kota' => '1971','provinsi_id' => '19','nama_kota' => 'KOTA PANGKAL PINANG'],
            ['id' => '2101','kode_kota' => '2101','provinsi_id' => '21','nama_kota' => 'KABUPATEN KARIMUN'],
            ['id' => '2102','kode_kota' => '2102','provinsi_id' => '21','nama_kota' => 'KABUPATEN BINTAN'],
            ['id' => '2103','kode_kota' => '2103','provinsi_id' => '21','nama_kota' => 'KABUPATEN NATUNA'],
            ['id' => '2104','kode_kota' => '2104','provinsi_id' => '21','nama_kota' => 'KABUPATEN LINGGA'],
            ['id' => '2105','kode_kota' => '2105','provinsi_id' => '21','nama_kota' => 'KABUPATEN KEPULAUAN ANAMBAS'],
            ['id' => '2171','kode_kota' => '2171','provinsi_id' => '21','nama_kota' => 'KOTA BATAM'],
            ['id' => '2172','kode_kota' => '2172','provinsi_id' => '21','nama_kota' => 'KOTA TANJUNG PINANG'],
            ['id' => '3101','kode_kota' => '3101','provinsi_id' => '31','nama_kota' => 'KABUPATEN KEPULAUAN SERIBU'],
            ['id' => '3171','kode_kota' => '3171','provinsi_id' => '31','nama_kota' => 'KOTA JAKARTA SELATAN'],
            ['id' => '3172','kode_kota' => '3172','provinsi_id' => '31','nama_kota' => 'KOTA JAKARTA TIMUR'],
            ['id' => '3173','kode_kota' => '3173','provinsi_id' => '31','nama_kota' => 'KOTA JAKARTA PUSAT'],
            ['id' => '3174','kode_kota' => '3174','provinsi_id' => '31','nama_kota' => 'KOTA JAKARTA BARAT'],
            ['id' => '3175','kode_kota' => '3175','provinsi_id' => '31','nama_kota' => 'KOTA JAKARTA UTARA'],
            ['id' => '3201','kode_kota' => '3201','provinsi_id' => '32','nama_kota' => 'KABUPATEN BOGOR'],
            ['id' => '3202','kode_kota' => '3202','provinsi_id' => '32','nama_kota' => 'KABUPATEN SUKABUMI'],
            ['id' => '3203','kode_kota' => '3203','provinsi_id' => '32','nama_kota' => 'KABUPATEN CIANJUR'],
            ['id' => '3204','kode_kota' => '3204','provinsi_id' => '32','nama_kota' => 'KABUPATEN BANDUNG'],
            ['id' => '3205','kode_kota' => '3205','provinsi_id' => '32','nama_kota' => 'KABUPATEN GARUT'],
            ['id' => '3206','kode_kota' => '3206','provinsi_id' => '32','nama_kota' => 'KABUPATEN TASIKMALAYA'],
            ['id' => '3207','kode_kota' => '3207','provinsi_id' => '32','nama_kota' => 'KABUPATEN CIAMIS'],
            ['id' => '3208','kode_kota' => '3208','provinsi_id' => '32','nama_kota' => 'KABUPATEN KUNINGAN'],
            ['id' => '3209','kode_kota' => '3209','provinsi_id' => '32','nama_kota' => 'KABUPATEN CIREBON'],
            ['id' => '3210','kode_kota' => '3210','provinsi_id' => '32','nama_kota' => 'KABUPATEN MAJALENGKA'],
            ['id' => '3211','kode_kota' => '3211','provinsi_id' => '32','nama_kota' => 'KABUPATEN SUMEDANG'],
            ['id' => '3212','kode_kota' => '3212','provinsi_id' => '32','nama_kota' => 'KABUPATEN INDRAMAYU'],
            ['id' => '3213','kode_kota' => '3213','provinsi_id' => '32','nama_kota' => 'KABUPATEN SUBANG'],
            ['id' => '3214','kode_kota' => '3214','provinsi_id' => '32','nama_kota' => 'KABUPATEN PURWAKARTA'],
            ['id' => '3215','kode_kota' => '3215','provinsi_id' => '32','nama_kota' => 'KABUPATEN KARAWANG'],
            ['id' => '3216','kode_kota' => '3216','provinsi_id' => '32','nama_kota' => 'KABUPATEN BEKASI'],
            ['id' => '3217','kode_kota' => '3217','provinsi_id' => '32','nama_kota' => 'KABUPATEN BANDUNG BARAT'],
            ['id' => '3218','kode_kota' => '3218','provinsi_id' => '32','nama_kota' => 'KABUPATEN PANGANDARAN'],
            ['id' => '3271','kode_kota' => '3271','provinsi_id' => '32','nama_kota' => 'KOTA BOGOR'],
            ['id' => '3272','kode_kota' => '3272','provinsi_id' => '32','nama_kota' => 'KOTA SUKABUMI'],
            ['id' => '3273','kode_kota' => '3273','provinsi_id' => '32','nama_kota' => 'KOTA BANDUNG'],
            ['id' => '3274','kode_kota' => '3274','provinsi_id' => '32','nama_kota' => 'KOTA CIREBON'],
            ['id' => '3275','kode_kota' => '3275','provinsi_id' => '32','nama_kota' => 'KOTA BEKASI'],
            ['id' => '3276','kode_kota' => '3276','provinsi_id' => '32','nama_kota' => 'KOTA DEPOK'],
            ['id' => '3277','kode_kota' => '3277','provinsi_id' => '32','nama_kota' => 'KOTA CIMAHI'],
            ['id' => '3278','kode_kota' => '3278','provinsi_id' => '32','nama_kota' => 'KOTA TASIKMALAYA'],
            ['id' => '3279','kode_kota' => '3279','provinsi_id' => '32','nama_kota' => 'KOTA BANJAR'],
            ['id' => '3301','kode_kota' => '3301','provinsi_id' => '33','nama_kota' => 'KABUPATEN CILACAP'],
            ['id' => '3302','kode_kota' => '3302','provinsi_id' => '33','nama_kota' => 'KABUPATEN BANYUMAS'],
            ['id' => '3303','kode_kota' => '3303','provinsi_id' => '33','nama_kota' => 'KABUPATEN PURBALINGGA'],
            ['id' => '3304','kode_kota' => '3304','provinsi_id' => '33','nama_kota' => 'KABUPATEN BANJARNEGARA'],
            ['id' => '3305','kode_kota' => '3305','provinsi_id' => '33','nama_kota' => 'KABUPATEN KEBUMEN'],
            ['id' => '3306','kode_kota' => '3306','provinsi_id' => '33','nama_kota' => 'KABUPATEN PURWOREJO'],
            ['id' => '3307','kode_kota' => '3307','provinsi_id' => '33','nama_kota' => 'KABUPATEN WONOSOBO'],
            ['id' => '3308','kode_kota' => '3308','provinsi_id' => '33','nama_kota' => 'KABUPATEN MAGELANG'],
            ['id' => '3309','kode_kota' => '3309','provinsi_id' => '33','nama_kota' => 'KABUPATEN BOYOLALI'],
            ['id' => '3310','kode_kota' => '3310','provinsi_id' => '33','nama_kota' => 'KABUPATEN KLATEN'],
            ['id' => '3311','kode_kota' => '3311','provinsi_id' => '33','nama_kota' => 'KABUPATEN SUKOHARJO'],
            ['id' => '3312','kode_kota' => '3312','provinsi_id' => '33','nama_kota' => 'KABUPATEN WONOGIRI'],
            ['id' => '3313','kode_kota' => '3313','provinsi_id' => '33','nama_kota' => 'KABUPATEN KARANGANYAR'],
            ['id' => '3314','kode_kota' => '3314','provinsi_id' => '33','nama_kota' => 'KABUPATEN SRAGEN'],
            ['id' => '3315','kode_kota' => '3315','provinsi_id' => '33','nama_kota' => 'KABUPATEN GROBOGAN'],
            ['id' => '3316','kode_kota' => '3316','provinsi_id' => '33','nama_kota' => 'KABUPATEN BLORA'],
            ['id' => '3317','kode_kota' => '3317','provinsi_id' => '33','nama_kota' => 'KABUPATEN REMBANG'],
            ['id' => '3318','kode_kota' => '3318','provinsi_id' => '33','nama_kota' => 'KABUPATEN PATI'],
            ['id' => '3319','kode_kota' => '3319','provinsi_id' => '33','nama_kota' => 'KABUPATEN KUDUS'],
            ['id' => '3320','kode_kota' => '3320','provinsi_id' => '33','nama_kota' => 'KABUPATEN JEPARA'],
            ['id' => '3321','kode_kota' => '3321','provinsi_id' => '33','nama_kota' => 'KABUPATEN DEMAK'],
            ['id' => '3322','kode_kota' => '3322','provinsi_id' => '33','nama_kota' => 'KABUPATEN SEMARANG'],
            ['id' => '3323','kode_kota' => '3323','provinsi_id' => '33','nama_kota' => 'KABUPATEN TEMANGGUNG'],
            ['id' => '3324','kode_kota' => '3324','provinsi_id' => '33','nama_kota' => 'KABUPATEN KENDAL'],
            ['id' => '3325','kode_kota' => '3325','provinsi_id' => '33','nama_kota' => 'KABUPATEN BATANG'],
            ['id' => '3326','kode_kota' => '3326','provinsi_id' => '33','nama_kota' => 'KABUPATEN PEKALONGAN'],
            ['id' => '3327','kode_kota' => '3327','provinsi_id' => '33','nama_kota' => 'KABUPATEN PEMALANG'],
            ['id' => '3328','kode_kota' => '3328','provinsi_id' => '33','nama_kota' => 'KABUPATEN TEGAL'],
            ['id' => '3329','kode_kota' => '3329','provinsi_id' => '33','nama_kota' => 'KABUPATEN BREBES'],
            ['id' => '3371','kode_kota' => '3371','provinsi_id' => '33','nama_kota' => 'KOTA MAGELANG'],
            ['id' => '3372','kode_kota' => '3372','provinsi_id' => '33','nama_kota' => 'KOTA SURAKARTA'],
            ['id' => '3373','kode_kota' => '3373','provinsi_id' => '33','nama_kota' => 'KOTA SALATIGA'],
            ['id' => '3374','kode_kota' => '3374','provinsi_id' => '33','nama_kota' => 'KOTA SEMARANG'],
            ['id' => '3375','kode_kota' => '3375','provinsi_id' => '33','nama_kota' => 'KOTA PEKALONGAN'],
            ['id' => '3376','kode_kota' => '3376','provinsi_id' => '33','nama_kota' => 'KOTA TEGAL'],
            ['id' => '3401','kode_kota' => '3401','provinsi_id' => '34','nama_kota' => 'KABUPATEN KULON PROGO'],
            ['id' => '3402','kode_kota' => '3402','provinsi_id' => '34','nama_kota' => 'KABUPATEN BANTUL'],
            ['id' => '3403','kode_kota' => '3403','provinsi_id' => '34','nama_kota' => 'KABUPATEN GUNUNG KIDUL'],
            ['id' => '3404','kode_kota' => '3404','provinsi_id' => '34','nama_kota' => 'KABUPATEN SLEMAN'],
            ['id' => '3471','kode_kota' => '3471','provinsi_id' => '34','nama_kota' => 'KOTA YOGYAKARTA'],
            ['id' => '3501','kode_kota' => '3501','provinsi_id' => '35','nama_kota' => 'KABUPATEN PACITAN'],
            ['id' => '3502','kode_kota' => '3502','provinsi_id' => '35','nama_kota' => 'KABUPATEN PONOROGO'],
            ['id' => '3503','kode_kota' => '3503','provinsi_id' => '35','nama_kota' => 'KABUPATEN TRENGGALEK'],
            ['id' => '3504','kode_kota' => '3504','provinsi_id' => '35','nama_kota' => 'KABUPATEN TULUNGAGUNG'],
            ['id' => '3505','kode_kota' => '3505','provinsi_id' => '35','nama_kota' => 'KABUPATEN BLITAR'],
            ['id' => '3506','kode_kota' => '3506','provinsi_id' => '35','nama_kota' => 'KABUPATEN KEDIRI'],
            ['id' => '3507','kode_kota' => '3507','provinsi_id' => '35','nama_kota' => 'KABUPATEN MALANG'],
            ['id' => '3508','kode_kota' => '3508','provinsi_id' => '35','nama_kota' => 'KABUPATEN LUMAJANG'],
            ['id' => '3509','kode_kota' => '3509','provinsi_id' => '35','nama_kota' => 'KABUPATEN JEMBER'],
            ['id' => '3510','kode_kota' => '3510','provinsi_id' => '35','nama_kota' => 'KABUPATEN BANYUWANGI'],
            ['id' => '3511','kode_kota' => '3511','provinsi_id' => '35','nama_kota' => 'KABUPATEN BONDOWOSO'],
            ['id' => '3512','kode_kota' => '3512','provinsi_id' => '35','nama_kota' => 'KABUPATEN SITUBONDO'],
            ['id' => '3513','kode_kota' => '3513','provinsi_id' => '35','nama_kota' => 'KABUPATEN PROBOLINGGO'],
            ['id' => '3514','kode_kota' => '3514','provinsi_id' => '35','nama_kota' => 'KABUPATEN PASURUAN'],
            ['id' => '3515','kode_kota' => '3515','provinsi_id' => '35','nama_kota' => 'KABUPATEN SIDOARJO'],
            ['id' => '3516','kode_kota' => '3516','provinsi_id' => '35','nama_kota' => 'KABUPATEN MOJOKERTO'],
            ['id' => '3517','kode_kota' => '3517','provinsi_id' => '35','nama_kota' => 'KABUPATEN JOMBANG'],
            ['id' => '3518','kode_kota' => '3518','provinsi_id' => '35','nama_kota' => 'KABUPATEN NGANJUK'],
            ['id' => '3519','kode_kota' => '3519','provinsi_id' => '35','nama_kota' => 'KABUPATEN MADIUN'],
            ['id' => '3520','kode_kota' => '3520','provinsi_id' => '35','nama_kota' => 'KABUPATEN MAGETAN'],
            ['id' => '3521','kode_kota' => '3521','provinsi_id' => '35','nama_kota' => 'KABUPATEN NGAWI'],
            ['id' => '3522','kode_kota' => '3522','provinsi_id' => '35','nama_kota' => 'KABUPATEN BOJONEGORO'],
            ['id' => '3523','kode_kota' => '3523','provinsi_id' => '35','nama_kota' => 'KABUPATEN TUBAN'],
            ['id' => '3524','kode_kota' => '3524','provinsi_id' => '35','nama_kota' => 'KABUPATEN LAMONGAN'],
            ['id' => '3525','kode_kota' => '3525','provinsi_id' => '35','nama_kota' => 'KABUPATEN GRESIK'],
            ['id' => '3526','kode_kota' => '3526','provinsi_id' => '35','nama_kota' => 'KABUPATEN BANGKALAN'],
            ['id' => '3527','kode_kota' => '3527','provinsi_id' => '35','nama_kota' => 'KABUPATEN SAMPANG'],
            ['id' => '3528','kode_kota' => '3528','provinsi_id' => '35','nama_kota' => 'KABUPATEN PAMEKASAN'],
            ['id' => '3529','kode_kota' => '3529','provinsi_id' => '35','nama_kota' => 'KABUPATEN SUMENEP'],
            ['id' => '3571','kode_kota' => '3571','provinsi_id' => '35','nama_kota' => 'KOTA KEDIRI'],
            ['id' => '3572','kode_kota' => '3572','provinsi_id' => '35','nama_kota' => 'KOTA BLITAR'],
            ['id' => '3573','kode_kota' => '3573','provinsi_id' => '35','nama_kota' => 'KOTA MALANG'],
            ['id' => '3574','kode_kota' => '3574','provinsi_id' => '35','nama_kota' => 'KOTA PROBOLINGGO'],
            ['id' => '3575','kode_kota' => '3575','provinsi_id' => '35','nama_kota' => 'KOTA PASURUAN'],
            ['id' => '3576','kode_kota' => '3576','provinsi_id' => '35','nama_kota' => 'KOTA MOJOKERTO'],
            ['id' => '3577','kode_kota' => '3577','provinsi_id' => '35','nama_kota' => 'KOTA MADIUN'],
            ['id' => '3578','kode_kota' => '3578','provinsi_id' => '35','nama_kota' => 'KOTA SURABAYA'],
            ['id' => '3579','kode_kota' => '3579','provinsi_id' => '35','nama_kota' => 'KOTA BATU'],
            ['id' => '3601','kode_kota' => '3601','provinsi_id' => '36','nama_kota' => 'KABUPATEN PANDEGLANG'],
            ['id' => '3602','kode_kota' => '3602','provinsi_id' => '36','nama_kota' => 'KABUPATEN LEBAK'],
            ['id' => '3603','kode_kota' => '3603','provinsi_id' => '36','nama_kota' => 'KABUPATEN TANGERANG'],
            ['id' => '3604','kode_kota' => '3604','provinsi_id' => '36','nama_kota' => 'KABUPATEN SERANG'],
            ['id' => '3671','kode_kota' => '3671','provinsi_id' => '36','nama_kota' => 'KOTA TANGERANG'],
            ['id' => '3672','kode_kota' => '3672','provinsi_id' => '36','nama_kota' => 'KOTA CILEGON'],
            ['id' => '3673','kode_kota' => '3673','provinsi_id' => '36','nama_kota' => 'KOTA SERANG'],
            ['id' => '3674','kode_kota' => '3674','provinsi_id' => '36','nama_kota' => 'KOTA TANGERANG SELATAN'],
            ['id' => '5101','kode_kota' => '5101','provinsi_id' => '51','nama_kota' => 'KABUPATEN JEMBRANA'],
            ['id' => '5102','kode_kota' => '5102','provinsi_id' => '51','nama_kota' => 'KABUPATEN TABANAN'],
            ['id' => '5103','kode_kota' => '5103','provinsi_id' => '51','nama_kota' => 'KABUPATEN BADUNG'],
            ['id' => '5104','kode_kota' => '5104','provinsi_id' => '51','nama_kota' => 'KABUPATEN GIANYAR'],
            ['id' => '5105','kode_kota' => '5105','provinsi_id' => '51','nama_kota' => 'KABUPATEN KLUNGKUNG'],
            ['id' => '5106','kode_kota' => '5106','provinsi_id' => '51','nama_kota' => 'KABUPATEN BANGLI'],
            ['id' => '5107','kode_kota' => '5107','provinsi_id' => '51','nama_kota' => 'KABUPATEN KARANG ASEM'],
            ['id' => '5108','kode_kota' => '5108','provinsi_id' => '51','nama_kota' => 'KABUPATEN BULELENG'],
            ['id' => '5171','kode_kota' => '5171','provinsi_id' => '51','nama_kota' => 'KOTA DENPASAR'],
            ['id' => '5201','kode_kota' => '5201','provinsi_id' => '52','nama_kota' => 'KABUPATEN LOMBOK BARAT'],
            ['id' => '5202','kode_kota' => '5202','provinsi_id' => '52','nama_kota' => 'KABUPATEN LOMBOK TENGAH'],
            ['id' => '5203','kode_kota' => '5203','provinsi_id' => '52','nama_kota' => 'KABUPATEN LOMBOK TIMUR'],
            ['id' => '5204','kode_kota' => '5204','provinsi_id' => '52','nama_kota' => 'KABUPATEN SUMBAWA'],
            ['id' => '5205','kode_kota' => '5205','provinsi_id' => '52','nama_kota' => 'KABUPATEN DOMPU'],
            ['id' => '5206','kode_kota' => '5206','provinsi_id' => '52','nama_kota' => 'KABUPATEN BIMA'],
            ['id' => '5207','kode_kota' => '5207','provinsi_id' => '52','nama_kota' => 'KABUPATEN SUMBAWA BARAT'],
            ['id' => '5208','kode_kota' => '5208','provinsi_id' => '52','nama_kota' => 'KABUPATEN LOMBOK UTARA'],
            ['id' => '5271','kode_kota' => '5271','provinsi_id' => '52','nama_kota' => 'KOTA MATARAM'],
            ['id' => '5272','kode_kota' => '5272','provinsi_id' => '52','nama_kota' => 'KOTA BIMA'],
            ['id' => '5301','kode_kota' => '5301','provinsi_id' => '53','nama_kota' => 'KABUPATEN SUMBA BARAT'],
            ['id' => '5302','kode_kota' => '5302','provinsi_id' => '53','nama_kota' => 'KABUPATEN SUMBA TIMUR'],
            ['id' => '5303','kode_kota' => '5303','provinsi_id' => '53','nama_kota' => 'KABUPATEN KUPANG'],
            ['id' => '5304','kode_kota' => '5304','provinsi_id' => '53','nama_kota' => 'KABUPATEN TIMOR TENGAH SELATAN'],
            ['id' => '5305','kode_kota' => '5305','provinsi_id' => '53','nama_kota' => 'KABUPATEN TIMOR TENGAH UTARA'],
            ['id' => '5306','kode_kota' => '5306','provinsi_id' => '53','nama_kota' => 'KABUPATEN BELU'],
            ['id' => '5307','kode_kota' => '5307','provinsi_id' => '53','nama_kota' => 'KABUPATEN ALOR'],
            ['id' => '5308','kode_kota' => '5308','provinsi_id' => '53','nama_kota' => 'KABUPATEN LEMBATA'],
            ['id' => '5309','kode_kota' => '5309','provinsi_id' => '53','nama_kota' => 'KABUPATEN FLORES TIMUR'],
            ['id' => '5310','kode_kota' => '5310','provinsi_id' => '53','nama_kota' => 'KABUPATEN SIKKA'],
            ['id' => '5311','kode_kota' => '5311','provinsi_id' => '53','nama_kota' => 'KABUPATEN ENDE'],
            ['id' => '5312','kode_kota' => '5312','provinsi_id' => '53','nama_kota' => 'KABUPATEN NGADA'],
            ['id' => '5313','kode_kota' => '5313','provinsi_id' => '53','nama_kota' => 'KABUPATEN MANGGARAI'],
            ['id' => '5314','kode_kota' => '5314','provinsi_id' => '53','nama_kota' => 'KABUPATEN ROTE NDAO'],
            ['id' => '5315','kode_kota' => '5315','provinsi_id' => '53','nama_kota' => 'KABUPATEN MANGGARAI BARAT'],
            ['id' => '5316','kode_kota' => '5316','provinsi_id' => '53','nama_kota' => 'KABUPATEN SUMBA TENGAH'],
            ['id' => '5317','kode_kota' => '5317','provinsi_id' => '53','nama_kota' => 'KABUPATEN SUMBA BARAT DAYA'],
            ['id' => '5318','kode_kota' => '5318','provinsi_id' => '53','nama_kota' => 'KABUPATEN NAGEKEO'],
            ['id' => '5319','kode_kota' => '5319','provinsi_id' => '53','nama_kota' => 'KABUPATEN MANGGARAI TIMUR'],
            ['id' => '5320','kode_kota' => '5320','provinsi_id' => '53','nama_kota' => 'KABUPATEN SABU RAIJUA'],
            ['id' => '5321','kode_kota' => '5321','provinsi_id' => '53','nama_kota' => 'KABUPATEN MALAKA'],
            ['id' => '5371','kode_kota' => '5371','provinsi_id' => '53','nama_kota' => 'KOTA KUPANG'],
            ['id' => '6101','kode_kota' => '6101','provinsi_id' => '61','nama_kota' => 'KABUPATEN SAMBAS'],
            ['id' => '6102','kode_kota' => '6102','provinsi_id' => '61','nama_kota' => 'KABUPATEN BENGKAYANG'],
            ['id' => '6103','kode_kota' => '6103','provinsi_id' => '61','nama_kota' => 'KABUPATEN LANDAK'],
            ['id' => '6104','kode_kota' => '6104','provinsi_id' => '61','nama_kota' => 'KABUPATEN MEMPAWAH'],
            ['id' => '6105','kode_kota' => '6105','provinsi_id' => '61','nama_kota' => 'KABUPATEN SANGGAU'],
            ['id' => '6106','kode_kota' => '6106','provinsi_id' => '61','nama_kota' => 'KABUPATEN KETAPANG'],
            ['id' => '6107','kode_kota' => '6107','provinsi_id' => '61','nama_kota' => 'KABUPATEN SINTANG'],
            ['id' => '6108','kode_kota' => '6108','provinsi_id' => '61','nama_kota' => 'KABUPATEN KAPUAS HULU'],
            ['id' => '6109','kode_kota' => '6109','provinsi_id' => '61','nama_kota' => 'KABUPATEN SEKADAU'],
            ['id' => '6110','kode_kota' => '6110','provinsi_id' => '61','nama_kota' => 'KABUPATEN MELAWI'],
            ['id' => '6111','kode_kota' => '6111','provinsi_id' => '61','nama_kota' => 'KABUPATEN KAYONG UTARA'],
            ['id' => '6112','kode_kota' => '6112','provinsi_id' => '61','nama_kota' => 'KABUPATEN KUBU RAYA'],
            ['id' => '6171','kode_kota' => '6171','provinsi_id' => '61','nama_kota' => 'KOTA PONTIANAK'],
            ['id' => '6172','kode_kota' => '6172','provinsi_id' => '61','nama_kota' => 'KOTA SINGKAWANG'],
            ['id' => '6201','kode_kota' => '6201','provinsi_id' => '62','nama_kota' => 'KABUPATEN KOTAWARINGIN BARAT'],
            ['id' => '6202','kode_kota' => '6202','provinsi_id' => '62','nama_kota' => 'KABUPATEN KOTAWARINGIN TIMUR'],
            ['id' => '6203','kode_kota' => '6203','provinsi_id' => '62','nama_kota' => 'KABUPATEN KAPUAS'],
            ['id' => '6204','kode_kota' => '6204','provinsi_id' => '62','nama_kota' => 'KABUPATEN BARITO SELATAN'],
            ['id' => '6205','kode_kota' => '6205','provinsi_id' => '62','nama_kota' => 'KABUPATEN BARITO UTARA'],
            ['id' => '6206','kode_kota' => '6206','provinsi_id' => '62','nama_kota' => 'KABUPATEN SUKAMARA'],
            ['id' => '6207','kode_kota' => '6207','provinsi_id' => '62','nama_kota' => 'KABUPATEN LAMANDAU'],
            ['id' => '6208','kode_kota' => '6208','provinsi_id' => '62','nama_kota' => 'KABUPATEN SERUYAN'],
            ['id' => '6209','kode_kota' => '6209','provinsi_id' => '62','nama_kota' => 'KABUPATEN KATINGAN'],
            ['id' => '6210','kode_kota' => '6210','provinsi_id' => '62','nama_kota' => 'KABUPATEN PULANG PISAU'],
            ['id' => '6211','kode_kota' => '6211','provinsi_id' => '62','nama_kota' => 'KABUPATEN GUNUNG MAS'],
            ['id' => '6212','kode_kota' => '6212','provinsi_id' => '62','nama_kota' => 'KABUPATEN BARITO TIMUR'],
            ['id' => '6213','kode_kota' => '6213','provinsi_id' => '62','nama_kota' => 'KABUPATEN MURUNG RAYA'],
            ['id' => '6271','kode_kota' => '6271','provinsi_id' => '62','nama_kota' => 'KOTA PALANGKA RAYA'],
            ['id' => '6301','kode_kota' => '6301','provinsi_id' => '63','nama_kota' => 'KABUPATEN TANAH LAUT'],
            ['id' => '6302','kode_kota' => '6302','provinsi_id' => '63','nama_kota' => 'KABUPATEN KOTA BARU'],
            ['id' => '6303','kode_kota' => '6303','provinsi_id' => '63','nama_kota' => 'KABUPATEN BANJAR'],
            ['id' => '6304','kode_kota' => '6304','provinsi_id' => '63','nama_kota' => 'KABUPATEN BARITO KUALA'],
            ['id' => '6305','kode_kota' => '6305','provinsi_id' => '63','nama_kota' => 'KABUPATEN TAPIN'],
            ['id' => '6306','kode_kota' => '6306','provinsi_id' => '63','nama_kota' => 'KABUPATEN HULU SUNGAI SELATAN'],
            ['id' => '6307','kode_kota' => '6307','provinsi_id' => '63','nama_kota' => 'KABUPATEN HULU SUNGAI TENGAH'],
            ['id' => '6308','kode_kota' => '6308','provinsi_id' => '63','nama_kota' => 'KABUPATEN HULU SUNGAI UTARA'],
            ['id' => '6309','kode_kota' => '6309','provinsi_id' => '63','nama_kota' => 'KABUPATEN TABALONG'],
            ['id' => '6310','kode_kota' => '6310','provinsi_id' => '63','nama_kota' => 'KABUPATEN TANAH BUMBU'],
            ['id' => '6311','kode_kota' => '6311','provinsi_id' => '63','nama_kota' => 'KABUPATEN BALANGAN'],
            ['id' => '6371','kode_kota' => '6371','provinsi_id' => '63','nama_kota' => 'KOTA BANJARMASIN'],
            ['id' => '6372','kode_kota' => '6372','provinsi_id' => '63','nama_kota' => 'KOTA BANJAR BARU'],
            ['id' => '6401','kode_kota' => '6401','provinsi_id' => '64','nama_kota' => 'KABUPATEN PASER'],
            ['id' => '6402','kode_kota' => '6402','provinsi_id' => '64','nama_kota' => 'KABUPATEN KUTAI BARAT'],
            ['id' => '6403','kode_kota' => '6403','provinsi_id' => '64','nama_kota' => 'KABUPATEN KUTAI KARTANEGARA'],
            ['id' => '6404','kode_kota' => '6404','provinsi_id' => '64','nama_kota' => 'KABUPATEN KUTAI TIMUR'],
            ['id' => '6405','kode_kota' => '6405','provinsi_id' => '64','nama_kota' => 'KABUPATEN BERAU'],
            ['id' => '6409','kode_kota' => '6409','provinsi_id' => '64','nama_kota' => 'KABUPATEN PENAJAM PASER UTARA'],
            ['id' => '6411','kode_kota' => '6411','provinsi_id' => '64','nama_kota' => 'KABUPATEN MAHAKAM HULU'],
            ['id' => '6471','kode_kota' => '6471','provinsi_id' => '64','nama_kota' => 'KOTA BALIKPAPAN'],
            ['id' => '6472','kode_kota' => '6472','provinsi_id' => '64','nama_kota' => 'KOTA SAMARINDA'],
            ['id' => '6474','kode_kota' => '6474','provinsi_id' => '64','nama_kota' => 'KOTA BONTANG'],
            ['id' => '6501','kode_kota' => '6501','provinsi_id' => '65','nama_kota' => 'KABUPATEN MALINAU'],
            ['id' => '6502','kode_kota' => '6502','provinsi_id' => '65','nama_kota' => 'KABUPATEN BULUNGAN'],
            ['id' => '6503','kode_kota' => '6503','provinsi_id' => '65','nama_kota' => 'KABUPATEN TANA TIDUNG'],
            ['id' => '6504','kode_kota' => '6504','provinsi_id' => '65','nama_kota' => 'KABUPATEN NUNUKAN'],
            ['id' => '6571','kode_kota' => '6571','provinsi_id' => '65','nama_kota' => 'KOTA TARAKAN'],
            ['id' => '7101','kode_kota' => '7101','provinsi_id' => '71','nama_kota' => 'KABUPATEN BOLAANG MONGONDOW'],
            ['id' => '7102','kode_kota' => '7102','provinsi_id' => '71','nama_kota' => 'KABUPATEN MINAHASA'],
            ['id' => '7103','kode_kota' => '7103','provinsi_id' => '71','nama_kota' => 'KABUPATEN KEPULAUAN SANGIHE'],
            ['id' => '7104','kode_kota' => '7104','provinsi_id' => '71','nama_kota' => 'KABUPATEN KEPULAUAN TALAUD'],
            ['id' => '7105','kode_kota' => '7105','provinsi_id' => '71','nama_kota' => 'KABUPATEN MINAHASA SELATAN'],
            ['id' => '7106','kode_kota' => '7106','provinsi_id' => '71','nama_kota' => 'KABUPATEN MINAHASA UTARA'],
            ['id' => '7107','kode_kota' => '7107','provinsi_id' => '71','nama_kota' => 'KABUPATEN BOLAANG MONGONDOW UTARA'],
            ['id' => '7108','kode_kota' => '7108','provinsi_id' => '71','nama_kota' => 'KABUPATEN SIAU TAGULANDANG BIARO'],
            ['id' => '7109','kode_kota' => '7109','provinsi_id' => '71','nama_kota' => 'KABUPATEN MINAHASA TENGGARA'],
            ['id' => '7110','kode_kota' => '7110','provinsi_id' => '71','nama_kota' => 'KABUPATEN BOLAANG MONGONDOW SELATAN'],
            ['id' => '7111','kode_kota' => '7111','provinsi_id' => '71','nama_kota' => 'KABUPATEN BOLAANG MONGONDOW TIMUR'],
            ['id' => '7171','kode_kota' => '7171','provinsi_id' => '71','nama_kota' => 'KOTA MANADO'],
            ['id' => '7172','kode_kota' => '7172','provinsi_id' => '71','nama_kota' => 'KOTA BITUNG'],
            ['id' => '7173','kode_kota' => '7173','provinsi_id' => '71','nama_kota' => 'KOTA TOMOHON'],
            ['id' => '7174','kode_kota' => '7174','provinsi_id' => '71','nama_kota' => 'KOTA KOTAMOBAGU'],
            ['id' => '7201','kode_kota' => '7201','provinsi_id' => '72','nama_kota' => 'KABUPATEN BANGGAI KEPULAUAN'],
            ['id' => '7202','kode_kota' => '7202','provinsi_id' => '72','nama_kota' => 'KABUPATEN BANGGAI'],
            ['id' => '7203','kode_kota' => '7203','provinsi_id' => '72','nama_kota' => 'KABUPATEN MOROWALI'],
            ['id' => '7204','kode_kota' => '7204','provinsi_id' => '72','nama_kota' => 'KABUPATEN POSO'],
            ['id' => '7205','kode_kota' => '7205','provinsi_id' => '72','nama_kota' => 'KABUPATEN DONGGALA'],
            ['id' => '7206','kode_kota' => '7206','provinsi_id' => '72','nama_kota' => 'KABUPATEN TOLI-TOLI'],
            ['id' => '7207','kode_kota' => '7207','provinsi_id' => '72','nama_kota' => 'KABUPATEN BUOL'],
            ['id' => '7208','kode_kota' => '7208','provinsi_id' => '72','nama_kota' => 'KABUPATEN PARIGI MOUTONG'],
            ['id' => '7209','kode_kota' => '7209','provinsi_id' => '72','nama_kota' => 'KABUPATEN TOJO UNA-UNA'],
            ['id' => '7210','kode_kota' => '7210','provinsi_id' => '72','nama_kota' => 'KABUPATEN SIGI'],
            ['id' => '7211','kode_kota' => '7211','provinsi_id' => '72','nama_kota' => 'KABUPATEN BANGGAI LAUT'],
            ['id' => '7212','kode_kota' => '7212','provinsi_id' => '72','nama_kota' => 'KABUPATEN MOROWALI UTARA'],
            ['id' => '7271','kode_kota' => '7271','provinsi_id' => '72','nama_kota' => 'KOTA PALU'],
            ['id' => '7301','kode_kota' => '7301','provinsi_id' => '73','nama_kota' => 'KABUPATEN KEPULAUAN SELAYAR'],
            ['id' => '7302','kode_kota' => '7302','provinsi_id' => '73','nama_kota' => 'KABUPATEN BULUKUMBA'],
            ['id' => '7303','kode_kota' => '7303','provinsi_id' => '73','nama_kota' => 'KABUPATEN BANTAENG'],
            ['id' => '7304','kode_kota' => '7304','provinsi_id' => '73','nama_kota' => 'KABUPATEN JENEPONTO'],
            ['id' => '7305','kode_kota' => '7305','provinsi_id' => '73','nama_kota' => 'KABUPATEN TAKALAR'],
            ['id' => '7306','kode_kota' => '7306','provinsi_id' => '73','nama_kota' => 'KABUPATEN GOWA'],
            ['id' => '7307','kode_kota' => '7307','provinsi_id' => '73','nama_kota' => 'KABUPATEN SINJAI'],
            ['id' => '7308','kode_kota' => '7308','provinsi_id' => '73','nama_kota' => 'KABUPATEN MAROS'],
            ['id' => '7309','kode_kota' => '7309','provinsi_id' => '73','nama_kota' => 'KABUPATEN PANGKAJENE DAN KEPULAUAN'],
            ['id' => '7310','kode_kota' => '7310','provinsi_id' => '73','nama_kota' => 'KABUPATEN BARRU'],
            ['id' => '7311','kode_kota' => '7311','provinsi_id' => '73','nama_kota' => 'KABUPATEN BONE'],
            ['id' => '7312','kode_kota' => '7312','provinsi_id' => '73','nama_kota' => 'KABUPATEN SOPPENG'],
            ['id' => '7313','kode_kota' => '7313','provinsi_id' => '73','nama_kota' => 'KABUPATEN WAJO'],
            ['id' => '7314','kode_kota' => '7314','provinsi_id' => '73','nama_kota' => 'KABUPATEN SIDENRENG RAPPANG'],
            ['id' => '7315','kode_kota' => '7315','provinsi_id' => '73','nama_kota' => 'KABUPATEN PINRANG'],
            ['id' => '7316','kode_kota' => '7316','provinsi_id' => '73','nama_kota' => 'KABUPATEN ENREKANG'],
            ['id' => '7317','kode_kota' => '7317','provinsi_id' => '73','nama_kota' => 'KABUPATEN LUWU'],
            ['id' => '7318','kode_kota' => '7318','provinsi_id' => '73','nama_kota' => 'KABUPATEN TANA TORAJA'],
            ['id' => '7322','kode_kota' => '7322','provinsi_id' => '73','nama_kota' => 'KABUPATEN LUWU UTARA'],
            ['id' => '7325','kode_kota' => '7325','provinsi_id' => '73','nama_kota' => 'KABUPATEN LUWU TIMUR'],
            ['id' => '7326','kode_kota' => '7326','provinsi_id' => '73','nama_kota' => 'KABUPATEN TORAJA UTARA'],
            ['id' => '7371','kode_kota' => '7371','provinsi_id' => '73','nama_kota' => 'KOTA MAKASSAR'],
            ['id' => '7372','kode_kota' => '7372','provinsi_id' => '73','nama_kota' => 'KOTA PAREPARE'],
            ['id' => '7373','kode_kota' => '7373','provinsi_id' => '73','nama_kota' => 'KOTA PALOPO'],
            ['id' => '7401','kode_kota' => '7401','provinsi_id' => '74','nama_kota' => 'KABUPATEN BUTON'],
            ['id' => '7402','kode_kota' => '7402','provinsi_id' => '74','nama_kota' => 'KABUPATEN MUNA'],
            ['id' => '7403','kode_kota' => '7403','provinsi_id' => '74','nama_kota' => 'KABUPATEN KONAWE'],
            ['id' => '7404','kode_kota' => '7404','provinsi_id' => '74','nama_kota' => 'KABUPATEN KOLAKA'],
            ['id' => '7405','kode_kota' => '7405','provinsi_id' => '74','nama_kota' => 'KABUPATEN KONAWE SELATAN'],
            ['id' => '7406','kode_kota' => '7406','provinsi_id' => '74','nama_kota' => 'KABUPATEN BOMBANA'],
            ['id' => '7407','kode_kota' => '7407','provinsi_id' => '74','nama_kota' => 'KABUPATEN WAKATOBI'],
            ['id' => '7408','kode_kota' => '7408','provinsi_id' => '74','nama_kota' => 'KABUPATEN KOLAKA UTARA'],
            ['id' => '7409','kode_kota' => '7409','provinsi_id' => '74','nama_kota' => 'KABUPATEN BUTON UTARA'],
            ['id' => '7410','kode_kota' => '7410','provinsi_id' => '74','nama_kota' => 'KABUPATEN KONAWE UTARA'],
            ['id' => '7411','kode_kota' => '7411','provinsi_id' => '74','nama_kota' => 'KABUPATEN KOLAKA TIMUR'],
            ['id' => '7412','kode_kota' => '7412','provinsi_id' => '74','nama_kota' => 'KABUPATEN KONAWE KEPULAUAN'],
            ['id' => '7413','kode_kota' => '7413','provinsi_id' => '74','nama_kota' => 'KABUPATEN MUNA BARAT'],
            ['id' => '7414','kode_kota' => '7414','provinsi_id' => '74','nama_kota' => 'KABUPATEN BUTON TENGAH'],
            ['id' => '7415','kode_kota' => '7415','provinsi_id' => '74','nama_kota' => 'KABUPATEN BUTON SELATAN'],
            ['id' => '7471','kode_kota' => '7471','provinsi_id' => '74','nama_kota' => 'KOTA KENDARI'],
            ['id' => '7472','kode_kota' => '7472','provinsi_id' => '74','nama_kota' => 'KOTA BAUBAU'],
            ['id' => '7501','kode_kota' => '7501','provinsi_id' => '75','nama_kota' => 'KABUPATEN BOALEMO'],
            ['id' => '7502','kode_kota' => '7502','provinsi_id' => '75','nama_kota' => 'KABUPATEN GORONTALO'],
            ['id' => '7503','kode_kota' => '7503','provinsi_id' => '75','nama_kota' => 'KABUPATEN POHUWATO'],
            ['id' => '7504','kode_kota' => '7504','provinsi_id' => '75','nama_kota' => 'KABUPATEN BONE BOLANGO'],
            ['id' => '7505','kode_kota' => '7505','provinsi_id' => '75','nama_kota' => 'KABUPATEN GORONTALO UTARA'],
            ['id' => '7571','kode_kota' => '7571','provinsi_id' => '75','nama_kota' => 'KOTA GORONTALO'],
            ['id' => '7601','kode_kota' => '7601','provinsi_id' => '76','nama_kota' => 'KABUPATEN MAJENE'],
            ['id' => '7602','kode_kota' => '7602','provinsi_id' => '76','nama_kota' => 'KABUPATEN POLEWALI MANDAR'],
            ['id' => '7603','kode_kota' => '7603','provinsi_id' => '76','nama_kota' => 'KABUPATEN MAMASA'],
            ['id' => '7604','kode_kota' => '7604','provinsi_id' => '76','nama_kota' => 'KABUPATEN MAMUJU'],
            ['id' => '7605','kode_kota' => '7605','provinsi_id' => '76','nama_kota' => 'KABUPATEN MAMUJU UTARA'],
            ['id' => '7606','kode_kota' => '7606','provinsi_id' => '76','nama_kota' => 'KABUPATEN MAMUJU TENGAH'],
            ['id' => '8101','kode_kota' => '8101','provinsi_id' => '81','nama_kota' => 'KABUPATEN MALUKU TENGGARA BARAT'],
            ['id' => '8102','kode_kota' => '8102','provinsi_id' => '81','nama_kota' => 'KABUPATEN MALUKU TENGGARA'],
            ['id' => '8103','kode_kota' => '8103','provinsi_id' => '81','nama_kota' => 'KABUPATEN MALUKU TENGAH'],
            ['id' => '8104','kode_kota' => '8104','provinsi_id' => '81','nama_kota' => 'KABUPATEN BURU'],
            ['id' => '8105','kode_kota' => '8105','provinsi_id' => '81','nama_kota' => 'KABUPATEN KEPULAUAN ARU'],
            ['id' => '8106','kode_kota' => '8106','provinsi_id' => '81','nama_kota' => 'KABUPATEN SERAM BAGIAN BARAT'],
            ['id' => '8107','kode_kota' => '8107','provinsi_id' => '81','nama_kota' => 'KABUPATEN SERAM BAGIAN TIMUR'],
            ['id' => '8108','kode_kota' => '8108','provinsi_id' => '81','nama_kota' => 'KABUPATEN MALUKU BARAT DAYA'],
            ['id' => '8109','kode_kota' => '8109','provinsi_id' => '81','nama_kota' => 'KABUPATEN BURU SELATAN'],
            ['id' => '8171','kode_kota' => '8171','provinsi_id' => '81','nama_kota' => 'KOTA AMBON'],
            ['id' => '8172','kode_kota' => '8172','provinsi_id' => '81','nama_kota' => 'KOTA TUAL'],
            ['id' => '8201','kode_kota' => '8201','provinsi_id' => '82','nama_kota' => 'KABUPATEN HALMAHERA BARAT'],
            ['id' => '8202','kode_kota' => '8202','provinsi_id' => '82','nama_kota' => 'KABUPATEN HALMAHERA TENGAH'],
            ['id' => '8203','kode_kota' => '8203','provinsi_id' => '82','nama_kota' => 'KABUPATEN KEPULAUAN SULA'],
            ['id' => '8204','kode_kota' => '8204','provinsi_id' => '82','nama_kota' => 'KABUPATEN HALMAHERA SELATAN'],
            ['id' => '8205','kode_kota' => '8205','provinsi_id' => '82','nama_kota' => 'KABUPATEN HALMAHERA UTARA'],
            ['id' => '8206','kode_kota' => '8206','provinsi_id' => '82','nama_kota' => 'KABUPATEN HALMAHERA TIMUR'],
            ['id' => '8207','kode_kota' => '8207','provinsi_id' => '82','nama_kota' => 'KABUPATEN PULAU MOROTAI'],
            ['id' => '8208','kode_kota' => '8208','provinsi_id' => '82','nama_kota' => 'KABUPATEN PULAU TALIABU'],
            ['id' => '8271','kode_kota' => '8271','provinsi_id' => '82','nama_kota' => 'KOTA TERNATE'],
            ['id' => '8272','kode_kota' => '8272','provinsi_id' => '82','nama_kota' => 'KOTA TIDORE KEPULAUAN'],
            ['id' => '9101','kode_kota' => '9101','provinsi_id' => '91','nama_kota' => 'KABUPATEN FAKFAK'],
            ['id' => '9102','kode_kota' => '9102','provinsi_id' => '91','nama_kota' => 'KABUPATEN KAIMANA'],
            ['id' => '9103','kode_kota' => '9103','provinsi_id' => '91','nama_kota' => 'KABUPATEN TELUK WONDAMA'],
            ['id' => '9104','kode_kota' => '9104','provinsi_id' => '91','nama_kota' => 'KABUPATEN TELUK BINTUNI'],
            ['id' => '9105','kode_kota' => '9105','provinsi_id' => '91','nama_kota' => 'KABUPATEN MANOKWARI'],
            ['id' => '9106','kode_kota' => '9106','provinsi_id' => '91','nama_kota' => 'KABUPATEN SORONG SELATAN'],
            ['id' => '9107','kode_kota' => '9107','provinsi_id' => '91','nama_kota' => 'KABUPATEN SORONG'],
            ['id' => '9108','kode_kota' => '9108','provinsi_id' => '91','nama_kota' => 'KABUPATEN RAJA AMPAT'],
            ['id' => '9109','kode_kota' => '9109','provinsi_id' => '91','nama_kota' => 'KABUPATEN TAMBRAUW'],
            ['id' => '9110','kode_kota' => '9110','provinsi_id' => '91','nama_kota' => 'KABUPATEN MAYBRAT'],
            ['id' => '9111','kode_kota' => '9111','provinsi_id' => '91','nama_kota' => 'KABUPATEN MANOKWARI SELATAN'],
            ['id' => '9112','kode_kota' => '9112','provinsi_id' => '91','nama_kota' => 'KABUPATEN PEGUNUNGAN ARFAK'],
            ['id' => '9171','kode_kota' => '9171','provinsi_id' => '91','nama_kota' => 'KOTA SORONG'],
            ['id' => '9401','kode_kota' => '9401','provinsi_id' => '94','nama_kota' => 'KABUPATEN MERAUKE'],
            ['id' => '9402','kode_kota' => '9402','provinsi_id' => '94','nama_kota' => 'KABUPATEN JAYAWIJAYA'],
            ['id' => '9403','kode_kota' => '9403','provinsi_id' => '94','nama_kota' => 'KABUPATEN JAYAPURA'],
            ['id' => '9404','kode_kota' => '9404','provinsi_id' => '94','nama_kota' => 'KABUPATEN NABIRE'],
            ['id' => '9408','kode_kota' => '9408','provinsi_id' => '94','nama_kota' => 'KABUPATEN KEPULAUAN YAPEN'],
            ['id' => '9409','kode_kota' => '9409','provinsi_id' => '94','nama_kota' => 'KABUPATEN BIAK NUMFOR'],
            ['id' => '9410','kode_kota' => '9410','provinsi_id' => '94','nama_kota' => 'KABUPATEN PANIAI'],
            ['id' => '9411','kode_kota' => '9411','provinsi_id' => '94','nama_kota' => 'KABUPATEN PUNCAK JAYA'],
            ['id' => '9412','kode_kota' => '9412','provinsi_id' => '94','nama_kota' => 'KABUPATEN MIMIKA'],
            ['id' => '9413','kode_kota' => '9413','provinsi_id' => '94','nama_kota' => 'KABUPATEN BOVEN DIGOEL'],
            ['id' => '9414','kode_kota' => '9414','provinsi_id' => '94','nama_kota' => 'KABUPATEN MAPPI'],
            ['id' => '9415','kode_kota' => '9415','provinsi_id' => '94','nama_kota' => 'KABUPATEN ASMAT'],
            ['id' => '9416','kode_kota' => '9416','provinsi_id' => '94','nama_kota' => 'KABUPATEN YAHUKIMO'],
            ['id' => '9417','kode_kota' => '9417','provinsi_id' => '94','nama_kota' => 'KABUPATEN PEGUNUNGAN BINTANG'],
            ['id' => '9418','kode_kota' => '9418','provinsi_id' => '94','nama_kota' => 'KABUPATEN TOLIKARA'],
            ['id' => '9419','kode_kota' => '9419','provinsi_id' => '94','nama_kota' => 'KABUPATEN SARMI'],
            ['id' => '9420','kode_kota' => '9420','provinsi_id' => '94','nama_kota' => 'KABUPATEN KEEROM'],
            ['id' => '9426','kode_kota' => '9426','provinsi_id' => '94','nama_kota' => 'KABUPATEN WAROPEN'],
            ['id' => '9427','kode_kota' => '9427','provinsi_id' => '94','nama_kota' => 'KABUPATEN SUPIORI'],
            ['id' => '9428','kode_kota' => '9428','provinsi_id' => '94','nama_kota' => 'KABUPATEN MAMBERAMO RAYA'],
            ['id' => '9429','kode_kota' => '9429','provinsi_id' => '94','nama_kota' => 'KABUPATEN NDUGA'],
            ['id' => '9430','kode_kota' => '9430','provinsi_id' => '94','nama_kota' => 'KABUPATEN LANNY JAYA'],
            ['id' => '9431','kode_kota' => '9431','provinsi_id' => '94','nama_kota' => 'KABUPATEN MAMBERAMO TENGAH'],
            ['id' => '9432','kode_kota' => '9432','provinsi_id' => '94','nama_kota' => 'KABUPATEN YALIMO'],
            ['id' => '9433','kode_kota' => '9433','provinsi_id' => '94','nama_kota' => 'KABUPATEN PUNCAK'],
            ['id' => '9434','kode_kota' => '9434','provinsi_id' => '94','nama_kota' => 'KABUPATEN DOGIYAI'],
            ['id' => '9435','kode_kota' => '9435','provinsi_id' => '94','nama_kota' => 'KABUPATEN INTAN JAYA'],
            ['id' => '9436','kode_kota' => '9436','provinsi_id' => '94','nama_kota' => 'KABUPATEN DEIYAI'],
            ['id' => '9471','kode_kota' => '9471','provinsi_id' => '94','nama_kota' => 'KOTA JAYAPURA'],

            // ['id' => '','kode_kota' => '','provinsi_id' => '','nama_kota' => ' '],



            ]);
    }
}